//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userTest()
        {
            this.userTestAnswers = new HashSet<userTestAnswer>();
        }
    
        public int userTestID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> testID { get; set; }
        public Nullable<int> marksScored { get; set; }
        public string statusOfTest { get; set; }
    
        public virtual test test { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userTestAnswer> userTestAnswers { get; set; }
    }
}
