//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OASEntities : DbContext, IOASEntities
    {
        public OASEntities()
            : base("name=OASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<category> categories { get; set; }
        public virtual IDbSet<role> roles { get; set; }
        public virtual IDbSet<subcategory> subcategories { get; set; }
        public virtual IDbSet<subcategoryTopic> subcategoryTopics { get; set; }
        public virtual IDbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual IDbSet<topic> topics { get; set; }
        public virtual IDbSet<userTest> userTests { get; set; }
        public virtual IDbSet<userTestAnswer> userTestAnswers { get; set; }
        public virtual IDbSet<testLog> testLogs { get; set; }
        public virtual IDbSet<test> tests { get; set; }
        public virtual IDbSet<question> questions { get; set; }
        public virtual IDbSet<user> users { get; set; }
    }
}
