//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class testLog
    {
        public Nullable<System.DateTime> testStarted { get; set; }
        public Nullable<System.DateTime> testEnded { get; set; }
        public Nullable<int> marksScored { get; set; }
        public Nullable<int> topicID { get; set; }
        public Nullable<int> userTestID { get; set; }
        public int testLogID { get; set; }
    
        public virtual topic topic { get; set; }
        public virtual userTest userTest { get; set; }
    }
}
