//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTestAnswer
    {
        public int userTestAnswerID { get; set; }
        public Nullable<int> userTestID { get; set; }
        public Nullable<int> questionID { get; set; }
        public string answerMarked { get; set; }
        public Nullable<int> srno { get; set; }
    
        public virtual userTest userTest { get; set; }
        public virtual question question { get; set; }
    }
}
