//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.userTests = new HashSet<userTest>();
        }
    
        public Nullable<int> roleID { get; set; }
        public int userID { get; set; }
        public string username { get; set; }
        public string passw { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<bool> is_Active { get; set; }
    
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userTest> userTests { get; set; }
    }
}
